#!/usr/bin/env python3
from pathlib import Path
p=Path('.github/workflows/build.yml'); s=p.read_text()
needle='''              NOTRIM_FLAG=""\n              if [ "${{ inputs.pixel_a9_compat }}" = "true" ] && [ "${{ inputs.image_only_compat }}" = "true" ]; then\n                echo "::error::Pixel A9 production compatibility cannot be combined with --notrim"\n                exit 1\n              elif [ "${{ inputs.image_only_compat }}" = "true" ]; then\n                echo "启用 Image-only system_dlkm 兼容模式: --notrim"\n                NOTRIM_FLAG="--notrim"\n              fi\n              tools/bazel build --disk_cache=/home/runner/.cache/bazel --config=fast $LTO_FLAG $NOTRIM_FLAG $FRAG_FLAG //common:kernel_aarch64_dist || exit 1\n'''
repl='''              NOTRIM_FLAG=""\n              if [ "${{ inputs.pixel_a9_compat }}" = "true" ] && [ "${{ inputs.image_only_compat }}" = "true" ]; then\n                echo "::error::Pixel A9 production compatibility cannot be combined with --notrim"\n                exit 1\n              elif [ "${{ inputs.image_only_compat }}" = "true" ]; then\n                echo "启用 Image-only system_dlkm 兼容模式: --notrim"\n                NOTRIM_FLAG="--notrim"\n              fi\n              STAMP_FLAG=""\n              if [ "${{ inputs.pixel_a9_compat }}" = "true" ]; then\n                echo "Pixel A9 mode: enabling Kleaf SCM stamping for g5c5f2fea42dd-ab15835541"\n                STAMP_FLAG="--config=stamp"\n              fi\n              tools/bazel build --disk_cache=/home/runner/.cache/bazel --config=fast $STAMP_FLAG $LTO_FLAG $NOTRIM_FLAG $FRAG_FLAG //common:kernel_aarch64_dist || exit 1\n'''
if s.count(needle)!=2: raise SystemExit(f'expected 2 image build blocks, got {s.count(needle)}')
s=s.replace(needle,repl)
needle2='''          DIST_DIR="$GITHUB_WORKSPACE/gki-dist/$CONFIG"\n          mkdir -p "$DIST_DIR"\n          tools/bazel run --disk_cache=/home/runner/.cache/bazel --config=fast \\\n            $LTO_FLAG $FRAG_FLAG //common:kernel_aarch64_dist -- --destdir="$DIST_DIR"\n'''
repl2='''          STAMP_FLAG=""\n          [ "${{ inputs.pixel_a9_compat }}" = "true" ] && STAMP_FLAG="--config=stamp"\n\n          DIST_DIR="$GITHUB_WORKSPACE/gki-dist/$CONFIG"\n          mkdir -p "$DIST_DIR"\n          tools/bazel run --disk_cache=/home/runner/.cache/bazel --config=fast \\\n            $STAMP_FLAG $LTO_FLAG $FRAG_FLAG //common:kernel_aarch64_dist -- --destdir="$DIST_DIR"\n'''
if s.count(needle2)!=1: raise SystemExit(f'expected 1 dist block, got {s.count(needle2)}')
s=s.replace(needle2,repl2); p.write_text(s)
